name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy --release --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose
